### ISSUE TITLE
How to run the program?

### ISSUE THREAD

**Issue by onlyonewater** [tanghaoyu258/ACRM-for-moment-retrieval#1]
Hi, can you provide the scripts to run ? When I use the command
 `python main.py --config-file=experiments/tacos_train.yaml`  
the error is as follow:
> 
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from config import cfg
  File "/home/dh/projects/ACRM-for-moment-retrieval/config/__init__.py", line 21, in <module>
    cfg.merge_from_file("config/solver/{}.yaml".format(cfg.SOLVER.TYPE.lower()))
  File "/home/dh/opt/anaconda3/envs/video-retrieval/lib/python3.7/site-packages/yacs/config.py", line 212, in merge_from_file
    cfg = self.load_cfg(f)
  File "/home/dh/opt/anaconda3/envs/video-retrieval/lib/python3.7/site-packages/yacs/config.py", line 349, in load_cfg
    return cls._load_cfg_from_file(cfg_file_obj_or_str)
  File "/home/dh/opt/anaconda3/envs/video-retrieval/lib/python3.7/site-packages/yacs/config.py", line 358, in _load_cfg_from_file
    return cls._load_cfg_from_yaml_str(file_obj.read())
  File "/home/dh/opt/anaconda3/envs/video-retrieval/lib/python3.7/site-packages/yacs/config.py", line 370, in _load_cfg_from_yaml_str
    cfg_as_dict = yaml.safe_load(str_obj)
  File "/home/dh/opt/anaconda3/envs/video-retrieval/lib/python3.7/site-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/home/dh/opt/anaconda3/envs/video-retrieval/lib/python3.7/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/home/dh/opt/anaconda3/envs/video-retrieval/lib/python3.7/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/home/dh/opt/anaconda3/envs/video-retrieval/lib/python3.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/home/dh/opt/anaconda3/envs/video-retrieval/lib/python3.7/site-packages/yaml/composer.py", line 58, in compose_document
    self.get_event()
  File "/home/dh/opt/anaconda3/envs/video-retrieval/lib/python3.7/site-packages/yaml/parser.py", line 118, in get_event
    self.current_event = self.state()
  File "/home/dh/opt/anaconda3/envs/video-retrieval/lib/python3.7/site-packages/yaml/parser.py", line 193, in parse_document_end
    token = self.peek_token()
  File "/home/dh/opt/anaconda3/envs/video-retrieval/lib/python3.7/site-packages/yaml/scanner.py", line 129, in peek_token
    self.fetch_more_tokens()
  File "/home/dh/opt/anaconda3/envs/video-retrieval/lib/python3.7/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "/home/dh/opt/anaconda3/envs/video-retrieval/lib/python3.7/site-packages/yaml/scanner.py", line 579, in fetch_value
    self.get_mark())
yaml.scanner.ScannerError: mapping values are not allowed here
  in "<unicode string>", line 128, column 34:
        <span style="background-color: #79b8ff;width: 0%;" class="Pro ... 
> 
Thanks!!!

**Comment by tanghaoyu258** [comment]
hi! i'm sorry but one file was missed in the previous version. I've uploaded this file and the code of building the model is also updated. I've tested the new version on my localhost with no error. Also, you should change the path of the 'glove embedding' in the line 23 of ./data/datasets/tacos.py. Ask me if you have any other questions.

**Comment by onlyonewater** [comment]
Hi, @tanghaoyu258, thank you for your reply, I will try it again. 
Thanks!!!

**Comment by onlyonewater** [comment]
Hi, @tanghaoyu258 , I read your code, I have a question, where are the codes for the cross-modal interaction section and attention module section of the paper? In ./modeling/localization_ACRM.py line 94, I only find the simple fusion code.

**Comment by tanghaoyu258** [comment]
hi. I‘m sorry but my code is not very elegant. The attention part is implemented in ./modeling/dynamic_filters/build.py  class EXCL_query. The original code of this part is in ./modeling/dynamic_filters/interactor.py, which is based on the the released code  of the paper 'Temporally Grounding Natural Sentence in Video'

**Comment by onlyonewater** [comment]
OK, I will read again.Thanks!!
